### PR TITLE
Se elimino el padding-bottom del body en Site.css

### PR DESCRIPTION
**Pull request by EliasPujols**
Esto de aqui:

capture2

Se corrige aqui:

capture1

### CODE REVIEW

**Comment by Willjobs94** [comment]
Try not to be a pirate, I guess you should first create an issue, so you can follow the convention of `feature/issueNumber-vainita` Ej. `feature/245-no-padding`. 

And also you should make the pull request from your feature against develop, so the feature is merged on develop after some code reviews and feedbacks, no before. 

You can also find more info about the git-flow guidelines on [this](https://www.youtube.com/watch?v=NmXcJh-yF8E) video made by the community itself.

Apart of this + 1

**Comment by eatskolnikov** [comment]
@EliasPujols lo que dijo @Willjobs94

**Comment by EliasPujols** [comment]
It's ok!

**Comment by claudiosanchez** [comment]
@EliasPujols Necesitas ayuda con esto?

**Comment by EliasPujols** [comment]
¿Con el issue?

**Comment by EliasPujols** [comment]
Con lo que comento @Willjobs94, ¿Es que cree el issue en cuanto al lo que he notificado?

**Comment by Willjobs94** [comment]
@EliasPujols creas el issue y el feature-branch de ese issue y haz el pull request a develop desde el feature branch.

**Comment by EliasPujols** [comment]
Perfecto, ahora mismo, aunque en Gitflow no se hace pull desde feature-branch sino desde develop.

**Comment by Willjobs94** [comment]
Well, according to [this guideline](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/) said that if you're using PR's you should create the PR in order to do code reviews and then merge it. If the team, does not use PR, then you can merge it local into develop.

**Comment by EliasPujols** [comment]
Ahora si estamos hablando.
Merege en develop desde feature-branch y luego puell request desde develop no desde feature (Gitflow)

**Comment by Willjobs94** [comment]
No, ve al link, dice que si el equipo está usando pull request debes hacerlo desde el feature-branch

**Comment by EliasPujols** [comment]
Perfect.

**Pull request closed without merging**
