### PR TITLE
Implement the categories feature layout

### PR DESCRIPTION
**Pull request by LuisAlbertoPenaNunez**
### This issue is related to #335 

# What's New

- This feature contains the layout for the categories feature from main page and it looks like this

screen shot 2016-03-22 at 11 59 36

This pull request contains a new service

### IBitmapResizer

Use this service to resize an image to avoid a friendly **OutOfMemoryError** 

### How? Easy buddy

`using(var bitmapToDisplay = _bitmapResizer.ResizeImageFromResources(resourceId,width, height))
image.SetImageBitmap(bitmapToDisplay);`

### CODE REVIEW

**Comment by Willjobs94** [comment]
What about the amount of job opportunities for each category ? on another Issue ?

**Comment by RaulMonteroC** [comment]
@Willjobs4 Remember this is only the MVP, right now only the essentials are built. We will keep working on top on that base code.

**Comment by Willjobs94** [comment]
You're right

**Comment by Willjobs94** [comment]
+1

**Comment by codnee** [comment]
I am concerned about your BitmapResizer. Your CalculateInSampleSize method uses the default outHeight and outWidth of the BitmapFactory.Options object. 

Aren't those defaults 0? That would basically make the method always return 1, since long as both the expected height and expected width will always be larger than 0.

**Pull request merged**
