### PR TITLE
Refactorizar algunas clases y agregar proyecto web api

### PR DESCRIPTION
**Pull request by jpozo20**
Tuve unos problemitas porque pensé que tenia el proyecto up-to-date y EF se quejaba de que el modelo había cambiado sin tener ningún cambio.

Supongo que habría que configurar el proyecto principal para que por ejemplo el endpoint api/jobs apunte al proyecto web api.

### CODE REVIEW

**Comment by Willjobs94** [comment]
Great work @jpozo20, there is a lot of changes to the code base and that means you're really excited to work and contribute. 

I would recommend you to separate the changes according to each feature/issue, you can use our [Contribution Guidelines](https://github.com/developersdo/empleo-dot-net/blob/develop/CONTRIBUTING.md) section so we can have a standardized way of contributing and make code reviews.

Also when you create the PR using the `features/issueNumber/feature-name` branch naming convention, include the issue number the PR is related to on the comment area, for faster and more intuitive navigation.

**Nice to have:** Do it in English, for the international community.

**Comment by jpozo20** [comment]
Thanks @Willjobs94, but besides a bit of refactoring (rename) most of the commits are related to the issues #90 and #421. What I did miss though was the branch name.

And really, there is not much change to the code base, it just that I added new projects and that's why some commits look kind of large. But of the rest of the solution I just touched a few files.

**Comment by Willjobs94** [comment]
Cool @jpozo20, then is only some git rebase required to changes the commit/branch name to follow the guidelines and to squash some commit message as well, after you finish with that, we can test it before merging.

Also if you fix something or include any documentation that was not part of the initial issue but is really just a minimal change you can include why you did those changes on the PR comment area.

**Comment by jpozo20** [comment]
Hello again, @Willjobs94 
I tried to do what you said, but rebasing doesn't change the branch name, it justs puts commits on top of another branch so I created another branch with the featurs/issue-name naming convention and rebased the webapi changes onto there.

So what should I do now? Create another pull request with the other branch and close or delete this?

**Comment by Willjobs94** [comment]
Yes @jpozo20, create a PR from the other branch

**Pull request closed without merging**
