### PR TITLE
Add web api for mobile clients

### PR DESCRIPTION
**Pull request by jpozo20**
Added a web API for the mobile client. This time I made the branch following the git workflow naming convention and the commits are cleaner and easier to understand:

-Added a Web API according to #90 and Unit Tests project, as well as Api.Contract to solution
-Deleted Home and Values controllers and views since we won't use them
-Added Ninject as DI Container
-Added NSubstitute, AutoFixture, and NUnit for the unit tests
-Added some Unit Tests, later o, will add more tests for the controllers

PS: The previous PR had some refactorings and renamings, this time I left them out and I'll open an issue before starting working on a PR for the changes.

CC : @Willjobs94

### CODE REVIEW

**Comment by Willjobs94** [comment]
Excellent work @jpozo20,  I see some CSS code, wich for me it means that they are UI changes, or new UI interfaces introduced, is that is the case, it's really great to provide a screenshot with the new UI Interface or a comparison with previous and actual UI look for the changes.

Also, there are still a lot of changes that can be separated into different branches, and what I mean is that some of the changes are not directly related to the issue you are trying to accomplish which is the #90. I do believe you are working hard, and really appreciate that for your part, but is better if we have only the related changes for the issue on each PR, unless it is really a minimal thing like deleting a comment or some minimal refactor. 

For me, it would be a great opportunity to do a Pair Programming with you and see how good you are and probably give you some more immediate feedback about what to do with this.

**Comment by jpozo20** [comment]
@Willjobs94 those are just the default files that come with the project, most of the changes come from the scaffold of creating the web project or adding packages. I think it's mainly due to the .js files that the changes look so big. 

But that is only on the first commit, if you look at the second and third commit they are small except for a few packages I had to add. 

In the meantime, I'll be looking at other issues until these changes are merged.

**Comment by Willjobs94** [comment]
@jpozo20 great you got a +1 them.

**Comment by jpozo20** [comment]
Will this ever be merged? 🤔

**Comment by jpozo20** [comment]
Thanks @eatskolnikov 😄

**Pull request merged**
