### PR TITLE
Display Job Count by Category in Search

### PR DESCRIPTION
**Pull request by luis-ramirez**
### What's New

- Added Job Count by Category in Search parameters

**UI Changes**
screen shot 2016-02-10 at 7 04 00 pm

### CODE REVIEW

**Comment by luis-ramirez** [comment]
Esto es resolviendo el unresolved conflcts en el OR #217

**Comment by luis-ramirez** [comment]
I need reviews of this :)

**Comment by jugomez** [comment]
Lo veo bien +1

**Comment by eatskolnikov** [comment]
+1

**Pull request merged**
