### PR TITLE
Add new template design

### PR DESCRIPTION
**Pull request by Willjobs94**
# What's new

- Restructure html to work with new template.

# Info 
This is not a complete working project with the new template, the idea is to share the MVP of the project with the new design on the server, allowing us to work simultaneously with multiple features at a time, just like we do it with develop.

We can also have an other branch called "new-design" or "new-template", cloned from this one.

### CODE REVIEW

**Comment by luis-ramirez** [comment]
No debería ser a develop, sino a otro branch para ir contribuyendo y no cambiar el esquema actual de trabajo

**Comment by luis-ramirez** [comment]
Hay que hacer un rebase y dejar un solo commit que diga:

**Added #278 New design template**

**Comment by luis-ramirez** [comment]
Tu branch tiene un problema con un package de nuget y esta haciendo que el actual CI no pueda compilar el código

screen shot 2016-02-26 at 8 44 42 am

**Comment by Willjobs94** [comment]
@luis-ramirez Thats, why I said that we can create another branch, and I guess I can't create it, because I don't have the permissions., I'll do the rebase and check the nuget package.
Thanks for feedbacks

**Comment by luis-ramirez** [comment]
acabo de encontrar un bug que esta en el codigo actual por esto, voy a hacer un hotfix debido a que esta en produccion actualmente

**Comment by Willjobs94** [comment]
+1 @luis-ramirez

**Pull request closed without merging**
